---
# tasks file for ldap_account_manager

- yum:
    name: "{{ item }}"
  with_items:
    - mod_ssl
    - php-ldap
    - http://prdownloads.sourceforge.net/lam/ldap-account-manager-{{ lam_version }}-0.fedora.1.noarch.rpm
    - http://prdownloads.sourceforge.net/lam/ldap-account-manager-lamdaemon-{{ lam_version }}-0.fedora.1.noarch.rpm


- template:
    src: lam.conf.j2
    dest: /var/lib/ldap-account-manager/config/lam.conf
    backup: yes
    owner: apache

- lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: ^Listen 80
    state: absent
  notify:
    - restart httpd

